### ISSUE TITLE
Hentoid may not have permission to write to SD card

### ISSUE THREAD

**Issue by wightwulf1944** [AVnetWS/Hentoid#50]
Affects version 1.1.4r2

Tested on: Samsung SM-G531H OS5.1.1

Screenshot:
![screenshot_2015-12-28-01-10-06](https://cloud.githubusercontent.com/assets/2737347/12011223/fe984684-acff-11e5-9c3d-dcb54a78c11a.png)

Repro steps:
1. On first launch activity, tap "EXPLORE"
2. Select SD card location
3. Tap "CONFIRM".
4. Tap "SAVE".

Result: A toast appears stating "You don't have permission to write in that folder, try in another folder"

Expected result: The user should be able to select sd card as the save location.

[Log](https://github.com/csaki/Hentoid/files/72746/log.txt)

[Reported here](http://fakkudroid.blogspot.com/2015/11/hentoid-v114.html?showComment=1449033972080#c518435025274968193) [and there.](http://fakkudroid.blogspot.com/2015/11/hentoid-v114.html?showComment=1450192260554#c2153220184624569402)

**Comment by avluis** [comment]
Just for clarification, this extSdCard does exist - and other applications can write to this folder as well?

**Comment by wightwulf1944** [comment]
Correct. The directory points to the root of the sd card and other apps csn read and write to it.

**Comment by avluis** [comment]
After much research, this phrase holds true:
Downloading to SD card is limited to certain directories only for Android 4.4.2 and above.

In order to make use of 'external SD storage' for newer Android versions, Hentoid will need to write to its private directory, and not via a public accessor - something that won't leave anyone happy if they find themselves unknowingly deleting their collection (when the app in uninstalled, the data goes as well).

**Comment by Interforce** [comment]
You can, however, completely disable that write protection (as I found it rather useless anyway).
Add "media_rw" group to **/system/etc/permissions/platform.xml** under WRITE_EXTERNAL_STORAGE and WRITE_MEDIA_STORAGE with a root-explorer:

    <permission name="android.permission.WRITE_EXTERNAL_STORAGE" >
        <group gid="sdcard_r" />
        <group gid="sdcard_rw" />
        <group gid="media_rw" />
    </permission>
    <permission name="android.permission.WRITE_MEDIA_STORAGE" >
        <group gid="sdcard_rw" />
        <group gid="media_rw" />
    </permission>

**Comment by avluis** [comment]
@Interforce Doesn't really help us there though - If the user wants to go ahead with this, they can, but its not something we can pull off app-level.
Thanks for sharing though.

**Comment by avluis** [comment]
Just [found something](http://stackoverflow.com/a/30514269/1615876) that may be really helpful~

**Comment by GlitcherWolf** [comment]
I believe [this](http://forum.xda-developers.com/showpost.php?p=66555451&postcount=28) could help a bit for MM. I also saw [an xposed module](http://repo.xposed.info/module/com.balamurugan.marshmallowsdfix) that did something similar to it. Perhaps it could be done on the app level because there is no further permissions check once the package installer is finished? Also, for those who have rooted phones, could you make the app ask for root permissions since SuperSU won't grant permissions without the app asking?

**Comment by avluis** [comment]
Thank you for the input -- but you are thinking in terms that do not apply to application development.
Hentoid is not restricted to rooted devices, so this should not even be considered.

No worries though, I'm already working on SD Card support.

**Comment by avluis** [comment]
Fixed under current [dev](/csaki/Hentoid/tree/dev) branch -- release will be up once further testing complete.
